apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pod-id-app-hpa-mem
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pod-id-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

