apiVersion: v1
kind: Service
metadata:
  name: pod-id-app-svc
  labels:
    app: pod-id-app
spec:
  selector:
    app: pod-id-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort
